# Site settings
title: VDoc maven plugin
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  VDoc maven plugin configuration and help
baseurl: "/vdoc-maven-plugin" # the subpath of your site, e.g. /blog/
url: "http://famaridon.github.io" # the base hostname & protocol for your site
github_username:  famaridon
github_repo: vdoc-maven-plugin
vdoc_maven_plugin_version: 14.1.0_SNAPSHOT
vdoc_current_version: 14.1

# Build settings
markdown: kramdown